
language: android
jdk:
     - oraclejdk8
android:
  components:
     - tools
     - platform-tools

    # The BuildTools version 
     - build-tools-19.1.0

    # The SDK version used to compile your project
     - android-22

    # Run emulator(s) during your tests
     - sys-img-armeabi-v7a-android-22
     - sys-img-armeabi-v7a-android-17

script: ./gradlew assembleDebug check
